export const FETCH_DATA_START = "FETCH_DATA_START";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";
export const CORRECT_GUESS = "CORRECT_GUESS";
export const ADD_TO_CART = "ADD_TO_CART";
export const EMPTY_CART = "REMOVE_FROM_CART";